### ISSUE TITLE
Typo: `mp3lame_encoder::Birtate` → `Bitrate`

### ISSUE THREAD

**Issue by SabrinaJewson** [DoumanAsh/mp3lame-encoder#1]
Looks like you accidentally typo’d this type as `Birtate` instead of `Bitrate`. Probably not worth a breaking release but save it for the next version.

**Comment by DoumanAsh** [comment]
Well we can correct it and make alias with invalid name

**Comment by DoumanAsh** [comment]
Fixed in https://github.com/DoumanAsh/mp3lame-encoder/commit/04a49af38e6bcc96bb8eb48078f0145458517105
