### ISSUE TITLE
mode MONO is missing from encoding mode enum

### ISSUE THREAD

**Issue by olup** [DoumanAsh/mp3lame-encoder#2]
All in the title, is that by design ?

**Comment by DoumanAsh** [comment]
lol I don't know why
I will add it

**Comment by olup** [comment]
Cool cheers. Will come in handy.

**Comment by DoumanAsh** [comment]
Note that you should always encode 1 channel with MONO mode
I'm not sure if LAME performs any sanity check so take care of that yourself

I released 0.1.3 with missing enum variant
