### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by psomani16k** [DoumanAsh/mp3lame-encoder#5]
There seems to be no way to embed an image into the encoded audio. Is there something I'm missing out?

**Comment by DoumanAsh** [comment]
I'm not sure what sort of images you mean, but mp3lame is for purpose of encoding audio only.
Do you want to create mp4 video?
Note that MP3 is container for audio only

**Comment by psomani16k** [comment]
I was refering to adding album art to the id3 tags (apologies for being so vague). mp3-lame-sys seems to have support for it.

**Comment by DoumanAsh** [comment]
Ah I see, that makes sense
I didn't add it because I was mostly needing minimal way to convert into mp3
I will add it later this week

**Comment by psomani16k** [comment]
Would you accept a pull request if I make one for the same?

**Comment by DoumanAsh** [comment]
Yes
Please make sure not to apply rustfmt though and follow the same style (empty slice indicates no value)

**Comment by DoumanAsh** [comment]
I added API to specify album art
This will be breaking change and I will release it as soon as valgrind tests passes
https://github.com/DoumanAsh/mp3lame-encoder/commit/c83c6a323a6668f207aa72d2f1ebd0398e615e65

Note that you need to make sure to allocate additional memory of at most 128k to store image

**Comment by DoumanAsh** [comment]
Released 0.2.0
